
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: collection_system
  password: <%= ENV["DB_PASS"] %>

development:
  <<: *default
  database: collection_system_development

test:
  <<: *default
  database: collection_system_test
  
production:
  <<: *default
  database: collection_system_production
